"""
Ctrl-Z FRC Team 4096
FIRST Robotics Competition 2019
Code for robot "----"
contact@team4096.org
"""

import math

"""
Prepend these to any IDs.
DIO = Digital I/O
AIN = Analog Input
PWM = Pulse Width Modulation
CAN = Controller Area Network
PCM = Pneumatic Control Module
PDP = Power Distribution Panel
"""

### CONSTANTS ###


## DRIVETRAIN ##

# MOTORS - all Victor SPs #
PWM_DRIVE_MOTOR_RIGHT_1					= 0
PWM_DRIVE_MOTOR_RIGHT_2					= 1
PWM_DRIVE_MOTOR_RIGHT_3					= 2

PWM_DRIVE_MOTOR_LEFT_1					= 3
PWM_DRIVE_MOTOR_LEFT_2					= 4
PWM_DRIVE_MOTOR_LEFT_3					= 5

# ENCODERS - grayhill encoders #
DIO_DRIVE_ENC_RIGHT_1					= 5
DIO_DRIVE_ENC_RIGHT_2					= 4

DIO_DRIVE_ENC_LEFT_1					= 7
DIO_DRIVE_ENC_LEFT_2					= 6

DRIVE_ENCODER_LEFT_REVERSED				= False			# NEED TO BE CHANGED
DRIVE_ENCODER_RIGHT_REVERSED			= False

DRIVE_CORRECTION_ENABLED				= False

DRIVE_WHEEL_DIAMETER_INCHES				= 6
DRIVE_ENCODER_TICKS_PER_REV				= 256
DRIVE_TICKS_PER_FOOT					= 12 / (math.pi * DRIVE_WHEEL_DIAMETER_INCHES / DRIVE_ENCODER_TICKS_PER_REV)

# Values from last year... might need to be changed
DRIVE_CORRECTION_ROTATION_THRESHOLD		= 0.05
DRIVE_CORRECTION_PROPORTION_FORWARD		= 0.1
DRIVE_CORRECTION_PROPORTION_REVERSE		= 0.04
DRIVE_CORRECTION_PROPORTION_FORWARD_ENC	= 0.009
DRIVE_CORRECTION_PROPORTION_REVERSE_ENC	= 0.009

DRIVE_ROTATION_MULTIPLIER 				= 0.85

# Minimum power required to move
# Minimum power required.
DRIVE_MIN_ROTATION_OUTPUT_TANK			= 0.5
DRIVE_MIN_OUTPUT_TANK 					= 0.5



## HATCH ##
# MOTORS #
CAN_MOTOR_HATCH_CARRIAGE				= 8

# STRING POTENTIOMETER #
AIN_HATCH_STRING_POT					= 2

# PRACTICE BOT VALUESSSS
HATCH_POT_MIN 							= 0.3174 / 5
HATCH_POT_MAX 							= 2.0801 / 5
HATCH_POT_RANGE_MIN 					= 0
HATCH_POT_RANGE_MAX 					= 11

HATCH_STRING_POT_MULTIPLIER 			= (HATCH_POT_RANGE_MAX - HATCH_POT_RANGE_MIN) / (HATCH_POT_MAX - HATCH_POT_MIN)
HATCH_STRING_POT_OFFSET 				= HATCH_POT_RANGE_MAX - (HATCH_POT_MAX * HATCH_STRING_POT_MULTIPLIER)

# PNEUMATICS #
PCM_HATCH_SOLENOID_BEAK_1				= 4			# PCM A
PCM_HATCH_SOLENOID_BEAK_2				= 5			# PCM A
PCM_HATCH_SOLENOID_CARRIAGE_1			= 2			# PCM A
PCM_HATCH_SOLENOID_CARRIAGE_2			= 3			# PCM A

# OTHER #
CARRIAGE_MIN							= 0.25
ARDUINO_DEVICE_ADDRESS					= 0x10
ARDUINO_LINE_SENSOR_MAX_VALUE			= 22

## CARGO ##
# MOTORS #
CAN_MOTOR_CARGO_ARM						= 5
CAN_MOTOR_CARGO_INTAKE					= 6

# POTENIOMETER #
AIN_CARGO_ARM_POT						= 1

# PRACTICE BOT VALUES
#pot min max need tweaking again
CARGO_POT_MIN 							= 0.80066 / 5
CARGO_POT_MAX 							= 2.8198 / 5
CARGO_POT_RANGE_MIN 					= 0
CARGO_POT_RANGE_MAX 					= 135

CARGO_ARM_POT_MULTIPLIER 				= (CARGO_POT_RANGE_MAX - CARGO_POT_RANGE_MIN) / (CARGO_POT_MAX - CARGO_POT_MIN)
CARGO_ARM_POT_OFFSET 					= CARGO_POT_RANGE_MAX - (CARGO_POT_MAX * CARGO_ARM_POT_MULTIPLIER)

# CURRENT SENSING #
CARGO_PDP_ID							= 4 # on comp bot
CARGO_INTAKE_THRESHOLD					= 10 # def needs to change

# PNEUMATICS #
PCM_CARGO_SOLENOID_BRAKE_1				= 0		# PCM A
PCM_CARGO_SOLENOID_BRAKE_2				= 1		# PCM A

# OTHER #
CARGO_MIN								= 0.25 		# change



## CLIMBER ##
CLIMB_SPEED								= 1.0
CLIMB_DISTANCE_CORRECTION_TOLERANCE		= 500	# How far apart the front/back climber pods need to be before they are corrected
CLIMB_SPEED_CORRECTION_MULTIPLIER		= 0.9	# Amount to slow down the faster of the two climber pods

# MOTORS #

CAN_MOTOR_CLIMBER_FRONT_AXLE			= 3
CAN_MOTOR_CLIMBER_BACK_AXLE				= 4
CAN_MOTOR_CLIMBER_FRONT_AXLE_DRIVE		= 7

# ENCODERS #
AIN_ULTRASONIC_FRONT					= 3
AIN_ULTRASONIC_REAR						= 4

ULTRASONIC_OVER_HAB_THRESHOLD			= 1000	# Min distance between readings that indicates it's over next Hab platform

# LIMIT SWITCHES #
DIO_CLIMBER_FRONT_TOP_LIMIT				= 0
DIO_CLIMBER_FRONT_BOTTOM_LIMIT			= 1
DIO_CLIMBER_BACK_TOP_LIMIT				= 2
DIO_CLIMBER_BACK_BOTTOM_LIMIT			= 3

# PNEUMATICS #
PCM_CLIMBER_FRONT_BRAKE_SOLENOID_1		= 0 	# PCM B
PCM_CLIMBER_FRONT_BRAKE_SOLENOID_2		= 1		# PCM B
PCM_CLIMBER_BACK_BRAKE_SOLENOID_1		= 6 	# PCM A
PCM_CLIMBER_BACK_BRAKE_SOLENOID_2		= 7 	# PCM A



## LIMELIGHT ##
DRIVER_CAMERA_MODE_ENABLED				= 1
DRIVER_CAMERA_MODE_DISABLED				= 0
DRIVER_CAMERA_MODE_DEFAULT				= DRIVER_CAMERA_MODE_ENABLED



### OTHER ###
AIN_PRESSURE_SENSOR 					= 0

# Labeled A on robot
CAN_PCM_A								= 1

# Labeled B on robot
CAN_PCM_B								= 2

CAN_PDP									= 0

CPROFILE_ENABLED						= False
